name: Production Deployment

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: new-sh-runner

    steps:
      - name: Build
        run: echo "Build Successful"

  deploy:
    needs: build
    runs-on: new-sh-runner
    environment: production

    steps:
      - name: Deploy Application
        run: echo "Deploying to Production"