name: test-sh-runner

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Build
        run: echo "Build Successful"

  notify:
    needs: build
    runs-on: self-hosted

    steps:
      - name: Notify Teams
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d '{
            "type":"AdaptiveCard",
            "$schema":"http://adaptivecards.io/schemas/adaptive-card.json",
            "version":"1.2",
            "body":[
              {
                "type":"TextBlock",
                "text":"GitHub Build Successful"
              }
            ]
          }' \
          "${{ secrets.TEAMS_WEBHOOK }}"